#!/bin/bash
#
# SPDX-License-Identifier: MIT
#
# Copyright (c) 2021-2022, Antonio Niño Díaz

set -e

# Paths to tools

export SUPERFAMICONV=${PWD}/SuperFamiconv/bin/superfamiconv
export UMOD_PACKER=${PWD}/umod-player/build/packer/umod_packer
export BIN2C=${PWD}/tools/build/bin2c/bin2c

# Build tools

pushd tools
rm -rf build ; mkdir build ; cd build
cmake ..
make
popd

if [ ! -d "${SUPERFAMICONV}" ]; then
    pushd SuperFamiconv
    make -j`nproc`
    popd
fi

if [ ! -d "${UMOD_PACKER}" ]; then
    pushd umod-player
    rm -rf build ; mkdir build ; cd build
    cmake ..
    make
    popd
fi

# Prepare destination folder

OUT_DIR=built_assets
rm -rf ${OUT_DIR}
mkdir ${OUT_DIR}

# Convert graphics

OUT_DIR_GRAPHICS=${OUT_DIR}/graphics
mkdir -p ${OUT_DIR_GRAPHICS}
bash graphics/convert.sh ${OUT_DIR_GRAPHICS}

# Convert music

mkdir ${OUT_DIR}/audio

${UMOD_PACKER} \
    ${OUT_DIR}/audio/umod_pack.bin \
    ${OUT_DIR}/audio/umod_pack_info.h \
    audio/*.mod \
    audio/*.wav

# Convert data

cp -r data built_assets

# Convert binary files generated by other stages

for dir in $(find built_assets -type d)
do
    for f in $(find $dir -maxdepth 1 -iname *.bin)
    do
        ${BIN2C} $f "$dir"
    done
done

# Done!

exit 0
