#!/bin/bash
#
# SPDX-License-Identifier: MIT
#
# Copyright (c) 2021, Antonio Niño Díaz

set -e

# Build tools

pushd tools
rm -rf build ; mkdir build ; cd build
cmake ..
make
popd

pushd SuperFamiconv
rm -rf build ; mkdir build ; cd build
cmake ..
make -j`nproc`
popd

pushd umod-player
rm -rf build ; mkdir build ; cd build
cmake ..
make
popd

# Paths to tools

export SUPERFAMICONV=SuperFamiconv/build/superfamiconv

# Prepare destination folder

OUT_DIR=built_assets
rm -rf ${OUT_DIR}
mkdir ${OUT_DIR}

# Convert graphics

OUT_DIR_GRAPHICS=${OUT_DIR}/graphics
mkdir -p ${OUT_DIR_GRAPHICS}
bash graphics/convert.sh ${OUT_DIR_GRAPHICS}

# Convert music

mkdir ${OUT_DIR}/audio

umod-player/build/packer/umod_packer \
    ${OUT_DIR}/audio/umod_pack.bin \
    ${OUT_DIR}/audio/umod_pack_info.h \
    audio/*.mod \
    audio/*.wav

# Convert data

cp -r data built_assets

# Convert binary files generated by other stages

for dir in $(find built_assets -type d)
do
    for f in $(find $dir -maxdepth 1 -iname *.bin)
    do
        tools/build/bin2c/bin2c $f "$dir"
    done
done

# Done!

exit 0
